# Generated by Django 4.1.3 on 2022-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_delete_userphoto_remove_article_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Upload File'),
        ),
    ]
